package com.polaris.ai.workflow.contract;

/** 持久化事件和 SSE 共用的稳定事件名称。 */
public enum WorkflowEventType {
    EXECUTION_QUEUED,
    EXECUTION_STARTED,
    EXECUTION_WAITING,
    EXECUTION_RECOVERING,
    EXECUTION_NEEDS_ATTENTION,
    EXECUTION_SUCCEEDED,
    EXECUTION_FAILED,
    EXECUTION_CANCELLED,
    EXECUTION_REJECTED,
    NODE_STARTED,
    NODE_OUTPUT,
    NODE_RETRY_SCHEDULED,
    NODE_SUCCEEDED,
    NODE_FAILED,
    NODE_SKIPPED,
    APPROVAL_CREATED,
    APPROVAL_DECIDED,
    USAGE_RECORDED
}
